import React, { useContext } from 'react'
import Head from 'next/head'
import { TitleContext } from '../reducer/Title.Reducer'
import { timeNow } from '../utils/Utils'

const Metadata = () => {
	console.log(
		`${timeNow()} --- [Metadata] --- Render at './component/Metadata.js'`
	)
	const titleCTX = useContext(TitleContext)

	return (
		<>
			<Head>
				<title>{titleCTX.state.name}</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='shortcut icon' href='/logo.ico' />
			</Head>
		</>
	)
}

export default React.memo(Metadata)
